[versions]
#jetbrains
kotlin = "2.3.0"
ksp = "2.3.2"
#Detekt
detekt = "1.23.8"
detektCompose = "0.4.28"
#AndroidX
androidx-swiperefreshlayout = "1.2.0"
androidx-documentfile = "1.1.0"
#Fossify
commons = "6.1.0"
#Other
autofittextview = "0.2.1"
gestureviews = "2.9.0"
glide = "5.0.5"
rootshell = "bc7e5d398e"
roottools = "965c154e20"
smbj = "0.14.0"
zip4j = "2.11.5"
#Gradle
gradlePlugins-agp = "9.0.0"
#build
app-build-compileSDKVersion = "36"
app-build-targetSDK = "36"
app-build-minimumSDK = "26"
app-build-javaVersion = "VERSION_21"
runtimeAndroid = "1.7.8"
uiAndroid = "1.7.8"
foundationLayoutAndroid = "1.7.8"
foundationAndroid = "1.7.8"
material3Android = "1.3.2"
uiTooling = "1.7.8"
[libraries]
#AndroidX
androidx-activity-compose = { module = "androidx.activity:activity-compose" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
#Compose
compose-detekt = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
#Fossify
fossify-commons = { module = "org.fossify:commons", version.ref = "commons" }
#Other
autofittextview = { module = "me.grantland:autofittextview", version.ref = "autofittextview" }
gestureviews = { module = "com.alexvasilkov:gesture-views", version.ref = "gestureviews" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideKsp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
rootshell = { module = "com.github.naveensingh:RootShell", version.ref = "rootshell" }
roottools = { module = "com.github.naveensingh:RootTools", version.ref = "roottools" }
smbj = { module = "com.hierynomus:smbj", version.ref = "smbj" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
androidx-foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version.ref = "foundationLayoutAndroid" }
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundationAndroid" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }